version: '3'
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama

  chatbot:
    build: .
    depends_on:
      - ollama
    environment:
      - BASE_URL=http://ollama:11434
    ports:
      - "5000:5000"

volumes:
  ollama:
