services:
  server:
    container_name: server_container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ollama
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: flask run
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]


volumes:
  ollama: